# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "discount-app-test-1"
client_id = "d7cd8aa19194b1aa92ae6fa1fc192921"
application_url = "https://recently-august-belief-providers.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,write_discounts"

[auth]
redirect_urls = [
  "https://recently-august-belief-providers.trycloudflare.com/auth/callback",
  "https://recently-august-belief-providers.trycloudflare.com/auth/shopify/callback",
  "https://recently-august-belief-providers.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "rivka-testing-store.myshopify.com"
