# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "discount-app-test-1"
client_id = "d7cd8aa19194b1aa92ae6fa1fc192921"
application_url = "https://admit-charged-pcs-asp.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,write_discounts"

[auth]
redirect_urls = [
  "https://admit-charged-pcs-asp.trycloudflare.com/auth/callback",
  "https://admit-charged-pcs-asp.trycloudflare.com/auth/shopify/callback",
  "https://admit-charged-pcs-asp.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false
